import pict from "./temp.png"

const menuItems = [
  {
    id: 0,
    name: "Борщ",
    category: "Суп",
    price: 320,
    weight: 300,
    photo: pict,
    count: 0,
  },
  {
    id: 1,
    name: "Рассольник",
    category: "Суп",
    price: 290,
    weight: 300,
    photo: pict,
    count: 0,
  },
  {
    id: 2,
    name: "Окрошка",
    category: "Суп",
    price: 270,
    weight: 300,
    photo: pict,
    count: 0,
  },
  {
    id: 3,
    name: "Стейк из говядины",
    category: "Горячее",
    price: 350,
    weight: 300,
    photo: pict,
    count: 0,
  },
  {
    id: 4,
    name: "Горшочек с картошкой и грибами",
    category: "Горячее",
    price: 350,
    weight: 300,
    photo: pict,
    count: 0,
  },
  {
    id: 5,
    name: "Мимоза",
    category: "Салат",
    price: 300,
    weight: 300,
    photo: pict,
    count: 0,
  },
  {
    id: 6,
    name: "Салат с морепродуктами",
    category: "Салат",
    price: 400,
    weight: 300,
    photo: pict,
    count: 0,
  },
  {
    id: 7,
    name: "Мороженное",
    category: "Десерт",
    price: 200,
    weight: 300,
    photo: pict,
    count: 0,
  },
];

export default menuItems;
