import pict from "./tempPhoto/menu-item-1.png"
import longpict from "./tempPhoto/menu-item-2.png"


export const menu = [
  {
    id: 0,
    name: "Борщ",
    category: "Суп",
    price: 320,
    weight: 300,
    weight_type: "мл",
    image: longpict,
  },
  {
    id: 1,
    name: "Рассольник",
    category: "Суп",
    price: 290,
    weight: 300,
    weight_type: "гр",
    image: pict,
  },
  {
    id: 2,
    name: "Окрошка",
    category: "Суп",
    price: 270,
    weight: 300,
    weight_type: "гр",
    image: longpict,
  },
  {
    id: 3,
    name: "Стейк из говядины",
    category: "Горячее",
    price: 350,
    weight: 300,
    weight_type: "гр",
    image: pict,
  },
  {
    id: 4,
    name: "Горшочек с картошкой и грибами",
    category: "Горячее",
    price: 350,
    weight: 300,
    weight_type: "гр",
    image: pict,
  },
  {
    id: 5,
    name: "Мимоза",
    category: "Салат",
    price: 300,
    weight: 300,
    weight_type: "гр",
    image: pict,
  },
  {
    id: 6,
    name: "Салат с морепродуктами",
    category: "Салат",
    price: 400,
    weight: 300,
    weight_type: "гр",
    image: pict,
  },
  {
    id: 7,
    name: "Мороженное",
    category: "Десерт",
    price: 200,
    weight: 300,
    weight_type: "гр",
    image: pict,
  },
];
