const menuItems = [
  {
    name: "Борщ",
    category: "Суп",
    price: 320,
    weight: 300,
    // photo: ,
    count: 0,
  },
  {
    name: "Рассольник",
    category: "Суп",
    price: 290,
    weight: 300,
    // photo: ,
    count: 0,
  },
  {
    name: "Окрошка",
    category: "Суп",
    price: 270,
    weight: 300,
    // photo: ,
    count: 0,
  },
  {
    name: "Стейк из говядины",
    category: "Горячее",
    price: 350,
    weight: 300,
    // photo: ,
    count: 3,
  },
  {
    name: "Горшочек с картошкой и грибами",
    category: "Горячее",
    price: 350,
    weight: 300,
    // photo: ,
    count: 0,
  },
  {
    name: "Мимоза",
    category: "Салат",
    price: 300,
    weight: 300,
    // photo: ,
    count: 0,
  },
  {
    name: "Салат с морепродуктами",
    category: "Салат",
    price: 400,
    weight: 300,
    // photo: ,
    count: 1,
  },
  {
    name: "Мороженное",
    category: "Десерт",
    price: 200,
    weight: 300,
    // photo: ,
    count: 0,
  },
];

export default menuItems;
